name: ci
on: push
jobs:
  job1:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::[1, 2, 3]"
  job2:
    needs: job1
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        containers: ${{fromJSON(needs.job1.outputs.matrix)}}
      fail-fast: false
    steps:
      - run: echo "Building ..."
