name: Using action
on: [push]

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      - id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3

  print:
    needs: prepare
    runs-on: ubuntu-20.04
    steps:
      - run: echo '${{jobs.prepare.outputs.matrix}}'
